### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by theodorosploumis** [theodorosploumis/drupal-lessons#1]
- [ ] Create Bundles per Level (eg for Students, Beginners, Junior Developers)
- [ ] Create Bundles per User role (eg for Themers, Developers, Site Builders)
- [ ] Estimate a duration per Lesson bundle
- [ ] Create icons for each bundle
